[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npx prisma db push && node src/index.js"
